/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Model.NinjaBond;
import Model.RepositorioBond;
import java.util.ArrayList;

/**
 *
 * @author Alex
 */
public class BondPanel extends javax.swing.JPanel {

    /**
     * Creates new form BondPanel
     */
    RepositorioBond m;
    SubBondPanel p1;
    SubBondPanel p2;
    SubBondPanel p3;
    SubBondPanel p4;
    SubBondPanel p5;
    SubBondPanel p6;
    SubBondPanel p7;
    SubBondPanel p8;
    SubBondPanel p9;
    
    
    public BondPanel(ArrayList <NinjaBond> data) {
        initComponents();
        m=new RepositorioBond(data);
        principal.setSize(1092, 718);
        addViews();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, 1092, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane principal;
    // End of variables declaration//GEN-END:variables

    private void addViews() {
       String [] order={"Team 7","Team 10","Team 8","Team 3","ANBU"};
       p1=new SubBondPanel((ArrayList<NinjaBond>) m.getData().clone(),"Ninja Team",order.clone());
       principal.addTab("Ninja Team", p1);
       String []order1={"Vermilion-South","Jewel-Azure","Three-North","White-Zero","Jewel-Black"};
       p2=new SubBondPanel((ArrayList<NinjaBond>) m.getData().clone(),"Akatsuki",order1.clone());
       principal.addTab("Akatsuki", p2);
       String []order2={"Special Tutor","Sannin","Life and death Bond","Taka","10-Tailed Jinchuuriki"};
       p3=new SubBondPanel((ArrayList<NinjaBond>) m.getData().clone(),"Special_Team",order2.clone());
       principal.addTab("Special Team", p3);
       String []order3={"Hokage","Tsuchikage","Mizukage","Raikage","Yellow Flash"};
       p4=new SubBondPanel((ArrayList<NinjaBond>) m.getData().clone(),"Kages",order3.clone());
       principal.addTab("Kages", p4);
       String []order4={"Susanoo","Konoha Guard","Six Paths Inheritance","Reanimation","Goddess"};
       p5=new SubBondPanel((ArrayList<NinjaBond>) m.getData().clone(),"Ninja World War",order4.clone());
       principal.addTab("Ninja World War", p5);
       String []order5={"Otsutsukis Heritage","Goddess Befalls","Brother Fight","Best Partners","Counterattack"};
       p6=new SubBondPanel((ArrayList<NinjaBond>) m.getData().clone(),"Super Squad",order5.clone());
       principal.addTab("Super Squad", p6);
       String []order6={"Alien Cursed","Alien Flower","Alien Swordsman","Uchiha three","Alien Shadow"};
       p7=new SubBondPanel((ArrayList<NinjaBond>) m.getData().clone(),"Alien Invasion",order6.clone());
       principal.addTab("Alien Invasion", p7);
       String []order7={"Final Team 7","Friendship Power","Hyga Smriti","Reanimated Shadow","Begining of Samsara"};
       p8=new SubBondPanel((ArrayList<NinjaBond>) m.getData().clone(),"Origin and Smriti",order7.clone());
       principal.addTab("Origin and Smriti", p8);
       String []order8={"Master and Servant","Illusory Reality","Warm-blood Comrade","Battleground Reverse","Demonstrated Beauty"};
       p9=new SubBondPanel((ArrayList<NinjaBond>) m.getData().clone(),"Ultima Awaken",order8.clone());
       principal.addTab("Ultima Awaken", p9);
       
       
    }
}
