/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Todomelocomo
 */
public class JadePanel extends javax.swing.JPanel {

    /**
     * Creates new form JadePanel
     */
    public JadePanel() {
        initComponents();
        setComboBox();
    }
    private void setComboBox(){
        jComboBox1.addItem("Force");
        jComboBox1.addItem("Agility");
        jComboBox1.addItem("Chakra");
        jComboBox1.addItem("Power");
        jComboBox1.addItem("Dodge");
        jComboBox1.addItem("Block");
        jComboBox1.addItem("Crit");
        jComboBox1.addItem("S Attack");
        jComboBox1.addItem("Counter");
        jComboBox1.addItem("Hit");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        jSpinner7 = new javax.swing.JSpinner();
        jSpinner6 = new javax.swing.JSpinner();
        jSpinner5 = new javax.swing.JSpinner();
        jSpinner8 = new javax.swing.JSpinner();
        jSpinner9 = new javax.swing.JSpinner();
        jSpinner10 = new javax.swing.JSpinner();
        jSpinner11 = new javax.swing.JSpinner();
        jSpinner12 = new javax.swing.JSpinner();
        Vip6 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        cuponsLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Agility/AGI_Jade_Lv.1.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(170, 100, 50, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Agility/AGI_Jade_Lv.12.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(670, 210, 50, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Agility/AGI_Jade_Lv.9.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(370, 210, 50, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Agility/AGI_Jade_Lv.10.png"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(470, 210, 50, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Agility/AGI_Jade_Lv.5.png"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(570, 100, 50, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Agility/AGI_Jade_Lv.6.png"))); // NOI18N
        add(jLabel6);
        jLabel6.setBounds(670, 100, 50, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Agility/AGI_Jade_Lv.11.png"))); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(570, 210, 50, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Agility/AGI_Jade_Lv.2.png"))); // NOI18N
        add(jLabel8);
        jLabel8.setBounds(270, 100, 50, 50);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Agility/AGI_Jade_Lv.1.png"))); // NOI18N
        add(jLabel15);
        jLabel15.setBounds(160, 420, 50, 50);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Agility/AGI_Jade_Lv.8.png"))); // NOI18N
        add(jLabel10);
        jLabel10.setBounds(270, 210, 50, 50);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Agility/AGI_Jade_Lv.3.png"))); // NOI18N
        add(jLabel11);
        jLabel11.setBounds(370, 100, 50, 50);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Agility/AGI_Jade_Lv.4.png"))); // NOI18N
        add(jLabel12);
        jLabel12.setBounds(470, 100, 50, 50);
        add(jSpinner1);
        jSpinner1.setBounds(169, 160, 50, 30);
        add(jSpinner3);
        jSpinner3.setBounds(370, 160, 50, 30);
        add(jSpinner2);
        jSpinner2.setBounds(270, 160, 50, 30);
        add(jSpinner4);
        jSpinner4.setBounds(470, 160, 50, 30);
        add(jSpinner7);
        jSpinner7.setBounds(170, 270, 50, 30);
        add(jSpinner6);
        jSpinner6.setBounds(669, 160, 50, 30);
        add(jSpinner5);
        jSpinner5.setBounds(570, 160, 50, 30);
        add(jSpinner8);
        jSpinner8.setBounds(270, 270, 50, 30);
        add(jSpinner9);
        jSpinner9.setBounds(370, 270, 50, 30);
        add(jSpinner10);
        jSpinner10.setBounds(470, 270, 50, 30);
        add(jSpinner11);
        jSpinner11.setBounds(570, 270, 50, 30);
        add(jSpinner12);
        jSpinner12.setBounds(670, 270, 50, 30);

        Vip6.setText("Vip6");
        Vip6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vip6ActionPerformed(evt);
            }
        });
        add(Vip6);
        Vip6.setBounds(818, 41, 60, 23);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1);
        jComboBox1.setBounds(22, 42, 90, 20);

        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(790, 180, 80, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Cupon.PNG"))); // NOI18N
        add(jLabel13);
        jLabel13.setBounds(170, 360, 30, 30);

        cuponsLabel.setText("Cupons : 0");
        add(cuponsLabel);
        cuponsLabel.setBounds(220, 370, 150, 14);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Agility/AGI_Jade_Lv.7.png"))); // NOI18N
        add(jLabel9);
        jLabel9.setBounds(170, 210, 50, 50);

        jLabel14.setText("lv 1 jades needed : 0");
        add(jLabel14);
        jLabel14.setBounds(230, 440, 140, 14);
    }// </editor-fold>//GEN-END:initComponents

    private void Vip6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vip6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Vip6ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String tipo=(String)jComboBox1.getSelectedItem();
        if(tipo.equals("Force")){
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Force/Force_Jade_Lv.1.png")));
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Force/Force_Jade_Lv.12.png"))); 
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Force/Force_Jade_Lv.9.png"))); 
            jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Force/Force_Jade_Lv.10.png")));
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Force/Force_Jade_Lv.5.png"))); 
            jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Force/Force_Jade_Lv.6.png"))); 
            jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Force/Force_Jade_Lv.11.png"))); 
            jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Force/Force_Jade_Lv.2.png")));
            jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Force/Force_Jade_Lv.7.png"))); 
            jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Force/Force_Jade_Lv.8.png")));
            jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Force/Force_Jade_Lv.3.png"))); 
            jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Force/Force_Jade_Lv.4.png")));
            jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Force/Force_Jade_Lv.1.png")));
        }else if(tipo.equals("Agility")){
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Agility/AGI_Jade_Lv.1.png")));
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Agility/AGI_Jade_Lv.12.png"))); 
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Agility/AGI_Jade_Lv.9.png"))); 
                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Agility/AGI_Jade_Lv.10.png")));
                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Agility/AGI_Jade_Lv.5.png"))); 
                jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Agility/AGI_Jade_Lv.6.png"))); 
                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Agility/AGI_Jade_Lv.11.png"))); 
                jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Agility/AGI_Jade_Lv.2.png")));
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Agility/AGI_Jade_Lv.7.png"))); 
                jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Agility/AGI_Jade_Lv.8.png")));
                jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Agility/AGI_Jade_Lv.3.png"))); 
                jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Agility/AGI_Jade_Lv.4.png")));
                jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Agility/AGI_Jade_Lv.1.png")));
        }else if(tipo.equals("Chakra")){
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Chakra/Chakra_Jade_Lv.1.png")));
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Chakra/Chakra_Jade_Lv.12.png"))); 
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Chakra/Chakra_Jade_Lv.9.png"))); 
                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Chakra/Chakra_Jade_Lv.10.png")));
                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Chakra/Chakra_Jade_Lv.5.png"))); 
                jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Chakra/Chakra_Jade_Lv.6.png"))); 
                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Chakra/Chakra_Jade_Lv.11.png"))); 
                jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Chakra/Chakra_Jade_Lv.2.png")));
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Chakra/Chakra_Jade_Lv.7.png"))); 
                jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Chakra/Chakra_Jade_Lv.8.png")));
                jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Chakra/Chakra_Jade_Lv.3.png"))); 
                jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Chakra/Chakra_Jade_Lv.4.png")));
                jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Chakra/Chakra_Jade_Lv.1.png")));
        }else if(tipo.equals("Power")){
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Power/Power_Jade_Lv.1.png")));
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Power/Power_Jade_Lv.12.png"))); 
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Power/Power_Jade_Lv.9.png"))); 
                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Power/Power_Jade_Lv.10.png")));
                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Power/Power_Jade_Lv.5.png"))); 
                jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Power/Power_Jade_Lv.6.png"))); 
                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Power/Power_Jade_Lv.11.png"))); 
                jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Power/Power_Jade_Lv.2.png")));
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Power/Power_Jade_Lv.7.png"))); 
                jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Power/Power_Jade_Lv.8.png")));
                jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Power/Power_Jade_Lv.3.png"))); 
                jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Power/Power_Jade_Lv.4.png")));
                jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Power/Power_Jade_Lv.1.png")));
        }else if(tipo.equals("Dodge")){
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Dodge/Dodge_Jade_Lv.1.png")));
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Dodge/Dodge_Jade_Lv.12.png"))); 
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Dodge/Dodge_Jade_Lv.9.png"))); 
                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Dodge/Dodge_Jade_Lv.10.png")));
                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Dodge/Dodge_Jade_Lv.5.png"))); 
                jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Dodge/Dodge_Jade_Lv.6.png"))); 
                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Dodge/Dodge_Jade_Lv.11.png"))); 
                jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Dodge/Dodge_Jade_Lv.2.png")));
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Dodge/Dodge_Jade_Lv.7.png"))); 
                jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Dodge/Dodge_Jade_Lv.8.png")));
                jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Dodge/Dodge_Jade_Lv.3.png"))); 
                jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Dodge/Dodge_Jade_Lv.4.png")));
                jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Dodge/Dodge_Jade_Lv.1.png")));
        }else if(tipo.equals("Block")){
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/block/Block_Jade_Lv.1.png")));
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/block/Block_Jade_Lv.12.png"))); 
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/block/Block_Jade_Lv.9.png"))); 
                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/block/Block_Jade_Lv.10.png")));
                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/block/Block_Jade_Lv.5.png"))); 
                jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/block/Block_Jade_Lv.6.png"))); 
                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/block/Block_Jade_Lv.11.png"))); 
                jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/block/Block_Jade_Lv.2.png")));
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/block/Block_Jade_Lv.7.png"))); 
                jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/block/Block_Jade_Lv.8.png")));
                jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/block/Block_Jade_Lv.3.png"))); 
                jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/block/Block_Jade_Lv.4.png")));
                jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/block/Block_Jade_Lv.1.png")));
        }else if(tipo.equals("Crit")){
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/critic/Crit_Jade_Lv.1.png")));
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/critic/Crit_Jade_Lv.12.png"))); 
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/critic/Crit_Jade_Lv.9.png"))); 
                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/critic/Crit_Jade_Lv.10.png")));
                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/critic/Crit_Jade_Lv.5.png"))); 
                jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/critic/Crit_Jade_Lv.6.png"))); 
                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/critic/Crit_Jade_Lv.11.png"))); 
                jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/critic/Crit_Jade_Lv.2.png")));
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/critic/Crit_Jade_Lv.7.png"))); 
                jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/critic/Crit_Jade_Lv.8.png")));
                jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/critic/Crit_Jade_Lv.3.png"))); 
                jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/critic/Crit_Jade_Lv.4.png")));
                jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/critic/Crit_Jade_Lv.1.png")));
        }else if(tipo.equals("S Attack")){
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Sattack/S_Attack_Jade_Lv.1.png")));
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Sattack/S_Attack_Jade_Lv.12.png"))); 
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Sattack/S_Attack_Jade_Lv.9.png"))); 
                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Sattack/S_Attack_Jade_Lv.10.png")));
                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Sattack/S_Attack_Jade_Lv.5.png"))); 
                jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Sattack/S_Attack_Jade_Lv.6.png"))); 
                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Sattack/S_Attack_Jade_Lv.11.png"))); 
                jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Sattack/S_Attack_Jade_Lv.2.png")));
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Sattack/S_Attack_Jade_Lv.7.png"))); 
                jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Sattack/S_Attack_Jade_Lv.8.png")));
                jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Sattack/S_Attack_Jade_Lv.3.png"))); 
                jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Sattack/S_Attack_Jade_Lv.4.png")));
                jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Sattack/S_Attack_Jade_Lv.1.png")));
        }else if(tipo.equals("Counter")){
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Counter/Counter_Jade_Lv.1.png")));
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Counter/Counter_Jade_Lv.12.png"))); 
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Counter/Counter_Jade_Lv.9.png"))); 
                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Counter/Counter_Jade_Lv.10.png")));
                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Counter/Counter_Jade_Lv.5.png"))); 
                jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Counter/Counter_Jade_Lv.6.png"))); 
                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Counter/Counter_Jade_Lv.11.png"))); 
                jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Counter/Counter_Jade_Lv.2.png")));
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Counter/Counter_Jade_Lv.7.png"))); 
                jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Counter/Counter_Jade_Lv.8.png")));
                jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Counter/Counter_Jade_Lv.3.png"))); 
                jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Counter/Counter_Jade_Lv.4.png")));
                jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Counter/Counter_Jade_Lv.1.png")));
        }else if(tipo.equals("Hit")){
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Hit/Hit_Jade_Lv.1.png")));
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Hit/Hit_Jade_Lv.12.png"))); 
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Hit/Hit_Jade_Lv.9.png"))); 
                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Hit/Hit_Jade_Lv.10.png")));
                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Hit/Hit_Jade_Lv.5.png"))); 
                jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Hit/Hit_Jade_Lv.6.png"))); 
                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Hit/Hit_Jade_Lv.11.png"))); 
                jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Hit/Hit_Jade_Lv.2.png")));
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Hit/Hit_Jade_Lv.7.png"))); 
                jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Hit/Hit_Jade_Lv.8.png")));
                jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Hit/Hit_Jade_Lv.3.png"))); 
                jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Hit/Hit_Jade_Lv.4.png")));
                jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Jades/Hit/Hit_Jade_Lv.1.png")));
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed
    int cupons=0;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int lv1=(int)jSpinner1.getValue();
        int lv2=(int)jSpinner2.getValue();
        int lv3=(int)jSpinner3.getValue();
        int lv4=(int)jSpinner4.getValue();
        int lv5=(int)jSpinner5.getValue();
        int lv6=(int)jSpinner6.getValue();
        int lv7=(int)jSpinner7.getValue();
        int lv8=(int)jSpinner8.getValue();
        int lv9=(int)jSpinner9.getValue();
        int lv10=(int)jSpinner10.getValue();
        int lv11=(int)jSpinner11.getValue();
        int lv12=(int)jSpinner12.getValue();
        cupons=0;
        if(Vip6.isSelected()){
        cupons+=lv1*12;
        cupons+=lv2*24;
        cupons+=lv3*48;
        cupons+=lv4*96;
        cupons+=lv5*192;
        cupons+=lv6*384;
        cupons+=lv7*768;
        cupons+=lv8*1536;
        cupons+=lv9*3072;
        cupons+=lv10*6144;
        cupons+=lv11*12288;
        cupons+=lv12*24576;
        cuponsLabel.setText("Cupons : "+ cupons);
        
        }else{
        cupons+=lv1*15;
        cupons+=lv2*30;
        cupons+=lv3*60;
        cupons+=lv4*120;
        cupons+=lv5*240;
        cupons+=lv6*480;
        cupons+=lv7*960;
        cupons+=lv8*1920;
        cupons+=lv9*3840;
        cupons+=lv10*7680;
        cupons+=lv11*15360;
        cupons+=lv12*30720;
        cuponsLabel.setText("Cupons : "+ cupons);   
        }
        int jades=0;
        jades+=lv1;
        jades+=lv2*2;
        jades+=lv3*4;
        jades+=lv4*8;
        jades+=lv5*16;
        jades+=lv6*32;
        jades+=lv7*64;
        jades+=lv8*128;
        jades+=lv9*256;
        jades+=lv10*512;
        jades+=lv11*1024;
        jades+=lv12*2048;
        jLabel14.setText("lv 1 jades needed : "+jades);
        
         
         
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Vip6;
    private javax.swing.JLabel cuponsLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner10;
    private javax.swing.JSpinner jSpinner11;
    private javax.swing.JSpinner jSpinner12;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JSpinner jSpinner8;
    private javax.swing.JSpinner jSpinner9;
    // End of variables declaration//GEN-END:variables
}
