/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Model.Model;
import Model.Potency;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Todomelocomo
 */
public class potencyPanel extends javax.swing.JPanel {

    /**
     * Creates new form potencyPanel
     */
    Model m;
    public potencyPanel(Model m) {
        initComponents();
        this.m=m;
        setPotencyOnTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        endLevel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        initialExpTextField = new javax.swing.JTextField();
        endLevelTextField = new javax.swing.JTextField();
        startLevelTextField = new javax.swing.JTextField();
        totalExpLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        smallPotencyLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bigPotencyLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        advancedPotencyLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        superPotencyLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        calculateButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        mediumPotencyLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenuItem1.setText("jMenuItem1");

        setLayout(null);

        jLabel1.setText("Start level");
        add(jLabel1);
        jLabel1.setBounds(32, 33, 71, 31);

        endLevel.setText("End  level");
        add(endLevel);
        endLevel.setBounds(32, 77, 71, 31);

        jLabel8.setText("Ninja initial exp");
        add(jLabel8);
        jLabel8.setBounds(32, 128, 116, 14);

        initialExpTextField.setText("0");
        initialExpTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initialExpTextFieldActionPerformed(evt);
            }
        });
        add(initialExpTextField);
        initialExpTextField.setBounds(158, 119, 136, 32);

        endLevelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endLevelTextFieldActionPerformed(evt);
            }
        });
        add(endLevelTextField);
        endLevelTextField.setBounds(158, 77, 136, 31);

        startLevelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startLevelTextFieldActionPerformed(evt);
            }
        });
        add(startLevelTextField);
        startLevelTextField.setBounds(158, 33, 137, 31);

        totalExpLabel.setText("Total Exp needed ");
        add(totalExpLabel);
        totalExpLabel.setBounds(30, 170, 262, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/potencyPanel/Small_Potency_Pill.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        add(jLabel6);
        jLabel6.setBounds(30, 220, 52, 48);

        smallPotencyLabel.setText("Small potency pills: 0");
        add(smallPotencyLabel);
        smallPotencyLabel.setBounds(120, 220, 230, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/potencyPanel/Big_Potency_Pill.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        add(jLabel4);
        jLabel4.setBounds(30, 360, 52, 51);

        bigPotencyLabel.setText("Big potency pills : 0");
        add(bigPotencyLabel);
        bigPotencyLabel.setBounds(120, 360, 240, 50);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/potencyPanel/Advanced_Potency_Pill.png"))); // NOI18N
        jLabel10.setText("jLabel2");
        add(jLabel10);
        jLabel10.setBounds(30, 430, 52, 50);

        advancedPotencyLabel.setText("Advanced potency pills : 0");
        add(advancedPotencyLabel);
        advancedPotencyLabel.setBounds(120, 430, 250, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/potencyPanel/Super_Potency_Pill.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(30, 500, 52, 50);

        superPotencyLabel.setText("Super potency pills : 0");
        add(superPotencyLabel);
        superPotencyLabel.setBounds(120, 500, 250, 50);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.setModel(marco);
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        add(jScrollPane1);
        jScrollPane1.setBounds(390, 20, 500, 435);

        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });
        add(calculateButton);
        calculateButton.setBounds(30, 650, 128, 41);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/potencyPanel/Medium_Potency_Pill.png"))); // NOI18N
        jLabel7.setText("jLabel6");
        add(jLabel7);
        jLabel7.setBounds(30, 290, 52, 48);

        mediumPotencyLabel.setText("Medium potency pills : 0");
        add(mediumPotencyLabel);
        mediumPotencyLabel.setBounds(120, 290, 240, 50);
        add(jLabel3);
        jLabel3.setBounds(390, 480, 500, 210);
    }// </editor-fold>//GEN-END:initComponents

    private void initialExpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initialExpTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_initialExpTextFieldActionPerformed

    private void endLevelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endLevelTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endLevelTextFieldActionPerformed

    private void startLevelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startLevelTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startLevelTextFieldActionPerformed
 
    
    private int start=-1;
    private int end=-1;
    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
        int filas []=Table.getSelectedRows();
        /*if(filas.length==1 && startLevelTextField.getText().isEmpty()){
            String aux=Table.get
        }else{
            static int
        }*/
        //String aux= Table.getR
        //System.out.println(Table.getSelectedRow());
        DefaultTableModel modelo = (DefaultTableModel) Table.getModel();
        int fila=Table.getSelectedRow();

        if(fila>-1 && startLevelTextField.getText().isEmpty()){
            startLevelTextField.setText((String)modelo.getValueAt(fila, 0));
            start=Table.getSelectedRow();
        }else{
            String temp=(String)modelo.getValueAt(fila, 0);
            if(Table.getSelectedRow()> end && Table.getSelectedRow()>start){
                // endLevelTextField.setText(temp);
                endLevelTextField.setText(temp);
                end=Table.getSelectedRow();
            }else{
                //startLevelTextField.setText((String)modelo.getValueAt(fila, 1));
                startLevelTextField.setText((String)modelo.getValueAt(fila, 0));
                start=Table.getSelectedRow();
            }
            
           
        }
         int level=Table.getSelectedRow();
            String levelText="";
            levelText+="Level : "+m.getPotency().get(level).getName()+"<br>"+"<br>";
            levelText+="Strategy/Physical Attack : "+m.getPotency().get(level).getAttack()+"<br>"+"<br>";
            levelText+="Strategy defense  : "+m.getPotency().get(level).getStrategyDefense()+"<br>"+"<br>";
            levelText+="Physical defense : "+m.getPotency().get(level).getPhysicalDefense()+"<br>"+"<br>";
            levelText+="Speed : "+m.getPotency().get(level).getSpeed()+"<br>"+"<br>";
            levelText+="HP : "+m.getPotency().get(level).getHealth()+"<br>";
            jLabel3.setText("<html>"+levelText);
            


    }//GEN-LAST:event_TableMouseClicked

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        // TODO add your handling code here:

        if(startLevelTextField.getText().isEmpty() || endLevelTextField.getText().isEmpty()){

        }else{
            String start_=startLevelTextField.getText();
            String end_=endLevelTextField.getText();
            int start1=0;//=Integer.parseInt(startLevelTextField.getText());
            int end1=0;//=Integer.parseInt(endLevelTextField.getText());
            int initialExp=Integer.parseInt(initialExpTextField.getText());
            
            for(int i=0;i<m.getPotency().size();i++){
                if(m.getPotency().get(i).getName().equals(start_)){
                    if(i==0){
                        start1=i+1;
                    }else{
                        start1=i;
                    }

                }
                if(m.getPotency().get(i).getName().equals(end_)){
                    end1=i;
                    System.out.println("Final encontrado en "+ i+ " e inicio en "+ start1);
                    break;
                }
            }
            long totalExp=0;
            int level=0;
            for(int i=start1;i<end1;i++){
                totalExp+=m.getPotency().get(i).getExp();
                level=i;
            }
            long smallPotency=totalExp/10;
            long mediumPotency=totalExp/50;
            long bigPotency=totalExp/100;
            long advancedPotency=totalExp/200;
            long superPotency=totalExp/500;
            totalExpLabel.setText("Total Exp needed "+(totalExp));
            smallPotencyLabel.setText("Small Potency Pills : "+(smallPotency+1));
            mediumPotencyLabel.setText("Medium Potency Pills : "+(mediumPotency+1));
            bigPotencyLabel.setText("Big Potency Pills : "+(bigPotency+1));
            advancedPotencyLabel.setText("Advanced Potency Pills :  "+(advancedPotency+1));
            superPotencyLabel.setText("Super Potency Pills : "+(superPotency+1));

            
            
        }
    }//GEN-LAST:event_calculateButtonActionPerformed

    
    DefaultTableModel marco = new DefaultTableModel(){
			@Override
			public boolean isCellEditable(int row, int column) {
				return false;
			}
		};
    private void setPotencyOnTable() {
        String [][] table=createTable();
        String [] titulos= new String []{
          "Name","Level","Exp"  
        };
        
        for(String s :titulos){
              marco.addColumn(s);
        }
        for(String [] s : table){
            marco.addRow(s);
        }
    }
    private String [][] createTable(){
        String matriz[][]=new String[m.getPotency().size()][4];
       
        ArrayList <Potency> aux=m.getPotency();
        for(int i=0;i<aux.size();i++){
            
            matriz[i][0]=aux.get(i).getName();
            matriz[i][1]=""+aux.get(i).getLv();
            matriz[i][2]=String.format("%d", aux.get(i).getExp());

        }
        return matriz;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JLabel advancedPotencyLabel;
    private javax.swing.JLabel bigPotencyLabel;
    private javax.swing.JButton calculateButton;
    private javax.swing.JLabel endLevel;
    private javax.swing.JTextField endLevelTextField;
    private javax.swing.JTextField initialExpTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mediumPotencyLabel;
    private javax.swing.JLabel smallPotencyLabel;
    private javax.swing.JTextField startLevelTextField;
    private javax.swing.JLabel superPotencyLabel;
    private javax.swing.JLabel totalExpLabel;
    // End of variables declaration//GEN-END:variables
}
