/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Model.RepositorioSenjutsu;
import Model.Senjutsu;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Todomelocomo
 */
public class SenjutsuPanel extends javax.swing.JPanel {

    /**
     * Creates new form SenjutsuPanel
     */
    private RepositorioSenjutsu m;
    public SenjutsuPanel(ArrayList <Senjutsu> m) {
        initComponents();
        this.m=new RepositorioSenjutsu(m);
        setLevels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        startLevelTextField = new javax.swing.JTextField();
        endLevel = new javax.swing.JLabel();
        endLevelTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        deityLabel = new javax.swing.JLabel();
        calculateButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        fairyLabel = new javax.swing.JLabel();
        totalExpLabel = new javax.swing.JLabel();
        statsLabel = new javax.swing.JLabel();
        statsLabel1 = new javax.swing.JLabel();

        jLabel1.setText("Start level");

        startLevelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startLevelTextFieldActionPerformed(evt);
            }
        });

        endLevel.setText("End  level");

        endLevelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endLevelTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Senjutsu/Deity.PNG"))); // NOI18N
        jLabel4.setText("jLabel4");

        deityLabel.setText("Deity : 0");

        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Senjutsu/Fairy.PNG"))); // NOI18N
        jLabel6.setText("jLabel6");

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.setModel(marco);
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        fairyLabel.setText("Fairy : 0");

        totalExpLabel.setText("Total Exp needed ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(startLevelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(deityLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                        .addComponent(fairyLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(endLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(endLevelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(totalExpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(statsLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(statsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175)))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startLevelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(endLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endLevelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(totalExpLabel)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fairyLabel))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statsLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(67, 67, 67))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void startLevelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startLevelTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startLevelTextFieldActionPerformed

    private void endLevelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endLevelTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endLevelTextFieldActionPerformed

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        // TODO add your handling code here:
        start=m.getLevel(startLevelTextField.getText());//;Integer.parseInt(startLevelTextField.getText());
        end=m.getLevel(endLevelTextField.getText());
        long totalExp=0;
        for(int i=start;i<end;i++){
            totalExp+=m.getData().get(i).getExp();
        }
        int fairy=(int) (totalExp/10);
        int deity=(int) (totalExp/10);
        totalExpLabel.setText("Totatl exp needed "+totalExp);
        fairyLabel.setText("Fairy : "+fairy);
        deityLabel.setText("Deity : "+deity);
        
    }//GEN-LAST:event_calculateButtonActionPerformed
    int start=-1;
    int end=-1;
    Senjutsu start1,end1;
    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
       
        DefaultTableModel modelo = (DefaultTableModel) Table.getModel();
        int fila=Table.getSelectedRow();
        Senjutsu aux= m.getData().get(fila);
        
        if(start==-1 || fila<start){
            start1=aux;
            start=fila;
            startLevelTextField.setText(start1.getName());
            statsLabel1.setText("<html>"+setStatsLabel(aux));
        }else if(end==-1 || fila>end ){
            end1=aux;
            end=fila;
            endLevelTextField.setText(end1.getName());
            statsLabel.setText("<html>"+setStatsLabel(aux));
        }else{
            start1=aux;
            start=fila;
            startLevelTextField.setText(start1.getName());
            statsLabel1.setText("<html>"+setStatsLabel(aux));
        }

    }//GEN-LAST:event_TableMouseClicked

     private String setStatsLabel(Senjutsu aux) {
        String text="";
        text+="Level      : "+aux.getName()+"<br>";
        text+="Exp level  : "+aux.getExp()+"<br>";
        text+="Force      : "+aux.getForce()+"<br>";
        text+="Chakra     : "+aux.getChakra()+"<br>";
        text+="Agi        : "+aux.getAgi()+"<br>";
        return text;  
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton calculateButton;
    private javax.swing.JLabel deityLabel;
    private javax.swing.JLabel endLevel;
    private javax.swing.JTextField endLevelTextField;
    private javax.swing.JLabel fairyLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField startLevelTextField;
    private javax.swing.JLabel statsLabel;
    private javax.swing.JLabel statsLabel1;
    private javax.swing.JLabel totalExpLabel;
    // End of variables declaration//GEN-END:variables

 DefaultTableModel marco = new DefaultTableModel(){
			@Override
			public boolean isCellEditable(int row, int column) {
				return false;
			}
		};
    private void setLevels() {
        String [][] table=createTable();
        String [] titulos= new String []{
          "Level","Exp",
        };
        
        for(String s :titulos){
              marco.addColumn(s);
        }
        for(String [] s : table){
            marco.addRow(s);
        }
    }
    private String [][] createTable(){
        String matriz[][]=new String[m.getData().size()][2];
       
        ArrayList <Senjutsu> aux=m.getData();
        for(int i=0;i<aux.size();i++){
            
            matriz[i][0]=aux.get(i).getName();
            matriz[i][1]=String.format("%d", aux.get(i).getExp());
          
            
        }
        return matriz;
    }

   

}
