/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Model.Level;
import Model.NinjaBond;
import Model.RepositorioBond;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alex
 */
public class SubBondPanel extends javax.swing.JPanel {

    /**
     * Creates new form subBondPanel
     */
    RepositorioBond m;
    String [] order;
    String name;
    public SubBondPanel(ArrayList <NinjaBond> data,String name,String order[]) {
        initComponents();
        m=new RepositorioBond(data);
        m.filtrar(name);
        this.name=name;
        this.order=order;
        setLevels();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable13 = new javax.swing.JTable();
        Foto1 = new javax.swing.JLabel();
        Foto4 = new javax.swing.JLabel();
        Foto2 = new javax.swing.JLabel();
        Foto5 = new javax.swing.JLabel();
        Foto3 = new javax.swing.JLabel();
        bond1 = new javax.swing.JLabel();
        bond2 = new javax.swing.JLabel();
        bond3 = new javax.swing.JLabel();
        bond5 = new javax.swing.JLabel();
        bond4 = new javax.swing.JLabel();
        bonus1 = new javax.swing.JLabel();
        bonus2 = new javax.swing.JLabel();
        bonus3 = new javax.swing.JLabel();
        bonus4 = new javax.swing.JLabel();
        bonus5 = new javax.swing.JLabel();
        toTextField = new javax.swing.JTextField();
        fromTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bonusLabel = new javax.swing.JLabel();
        fromLabel = new javax.swing.JLabel();
        toLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BonusLabel5 = new javax.swing.JLabel();
        BonusLabel1 = new javax.swing.JLabel();
        BonusLabel2 = new javax.swing.JLabel();
        BonusLabel3 = new javax.swing.JLabel();
        BonusLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        purpleSoulLabel = new javax.swing.JLabel();
        yellowSoulLabel = new javax.swing.JLabel();
        redSoulLabel = new javax.swing.JLabel();
        bluesoulLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        goldLabel = new javax.swing.JLabel();

        jTable13.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable13);

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        setLayout(null);

        Foto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Foto1.setText("jLabel1");
        add(Foto1);
        Foto1.setBounds(270, 50, 130, 80);

        Foto4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Foto4.setText("jLabel1");
        add(Foto4);
        Foto4.setBounds(740, 50, 130, 80);

        Foto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Foto2.setText("jLabel1");
        add(Foto2);
        Foto2.setBounds(420, 50, 130, 80);

        Foto5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Bonds/Ninja Team/Team 7.PNG"))); // NOI18N
        Foto5.setText("jLabel1");
        add(Foto5);
        Foto5.setBounds(890, 50, 130, 84);

        Foto3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Foto3.setText("jLabel1");
        add(Foto3);
        Foto3.setBounds(580, 50, 130, 80);

        bond1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bond1.setText("jLabel1");
        add(bond1);
        bond1.setBounds(270, 160, 130, 10);

        bond2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bond2.setText("jLabel1");
        add(bond2);
        bond2.setBounds(430, 160, 122, 10);

        bond3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bond3.setText("jLabel1");
        add(bond3);
        bond3.setBounds(580, 160, 130, 10);

        bond5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bond5.setText("jLabel1");
        add(bond5);
        bond5.setBounds(890, 160, 130, 10);

        bond4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bond4.setText("jLabel1");
        add(bond4);
        bond4.setBounds(750, 160, 110, 10);

        bonus1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bonus1.setText("jLabel1");
        add(bonus1);
        bonus1.setBounds(270, 200, 130, 10);

        bonus2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bonus2.setText("jLabel1");
        add(bonus2);
        bonus2.setBounds(430, 200, 122, 10);

        bonus3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bonus3.setText("jLabel1");
        add(bonus3);
        bonus3.setBounds(580, 200, 130, 10);

        bonus4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bonus4.setText("jLabel1");
        add(bonus4);
        bonus4.setBounds(740, 200, 120, 10);

        bonus5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bonus5.setText("jLabel1");
        add(bonus5);
        bonus5.setBounds(890, 200, 130, 14);

        toTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toTextFieldActionPerformed(evt);
            }
        });
        add(toTextField);
        toTextField.setBounds(90, 80, 60, 30);

        fromTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromTextFieldActionPerformed(evt);
            }
        });
        add(fromTextField);
        fromTextField.setBounds(90, 20, 59, 30);

        jLabel1.setText("To");
        add(jLabel1);
        jLabel1.setBounds(30, 90, 40, 20);

        jLabel2.setText("From");
        add(jLabel2);
        jLabel2.setBounds(30, 30, 40, 20);
        add(bonusLabel);
        bonusLabel.setBounds(90, 370, 100, 120);
        add(fromLabel);
        fromLabel.setBounds(90, 120, 100, 110);
        add(toLabel);
        toLabel.setBounds(90, 240, 100, 120);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(270, 270, 130, 200);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        add(jScrollPane3);
        jScrollPane3.setBounds(420, 270, 130, 200);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        add(jScrollPane4);
        jScrollPane4.setBounds(580, 270, 130, 200);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable4);

        add(jScrollPane5);
        jScrollPane5.setBounds(740, 270, 130, 200);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable5);

        add(jScrollPane6);
        jScrollPane6.setBounds(890, 270, 130, 200);

        jLabel4.setText("Bonus");
        add(jLabel4);
        jLabel4.setBounds(20, 420, 50, 14);

        jLabel5.setText("From");
        add(jLabel5);
        jLabel5.setBounds(30, 170, 34, 14);

        jLabel6.setText("To");
        add(jLabel6);
        jLabel6.setBounds(30, 300, 34, 14);

        BonusLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BonusLabel5.setText("jLabel3");
        add(BonusLabel5);
        BonusLabel5.setBounds(270, 630, 710, 20);

        BonusLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BonusLabel1.setText("jLabel3");
        add(BonusLabel1);
        BonusLabel1.setBounds(270, 510, 710, 20);

        BonusLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BonusLabel2.setText("jLabel3");
        add(BonusLabel2);
        BonusLabel2.setBounds(270, 540, 710, 20);

        BonusLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BonusLabel3.setText("jLabel3");
        add(BonusLabel3);
        BonusLabel3.setBounds(270, 570, 710, 20);

        BonusLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BonusLabel4.setText("jLabel3");
        add(BonusLabel4);
        BonusLabel4.setBounds(270, 600, 710, 20);

        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(940, 660, 90, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Souls/yellowsoul.PNG"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3);
        jLabel3.setBounds(30, 590, 30, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Souls/bluesoul.PNG"))); // NOI18N
        jLabel7.setText("jLabel3");
        add(jLabel7);
        jLabel7.setBounds(30, 510, 30, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Souls/redsoul.PNG"))); // NOI18N
        jLabel8.setText("jLabel3");
        add(jLabel8);
        jLabel8.setBounds(30, 630, 30, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Souls/purplesoul.PNG"))); // NOI18N
        jLabel9.setText("jLabel3");
        add(jLabel9);
        jLabel9.setBounds(30, 550, 30, 30);

        purpleSoulLabel.setText("Purple souls : 0");
        add(purpleSoulLabel);
        purpleSoulLabel.setBounds(90, 560, 180, 14);

        yellowSoulLabel.setText("Yellow souls : 0");
        add(yellowSoulLabel);
        yellowSoulLabel.setBounds(90, 600, 180, 14);

        redSoulLabel.setText("Red souls : 0");
        add(redSoulLabel);
        redSoulLabel.setBounds(90, 640, 180, 14);

        bluesoulLabel.setText("Blue souls : 0");
        add(bluesoulLabel);
        bluesoulLabel.setBounds(90, 520, 180, 14);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Souls/gold.PNG"))); // NOI18N
        jLabel10.setText("jLabel3");
        add(jLabel10);
        jLabel10.setBounds(30, 670, 30, 30);

        goldLabel.setText("Gold : 0");
        add(goldLabel);
        goldLabel.setBounds(90, 680, 180, 14);
    }// </editor-fold>//GEN-END:initComponents

    private void toTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toTextFieldActionPerformed

    private void fromTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int i,f;
      
        try{
         i=Integer.parseInt(fromTextField.getText());
         f=Integer.parseInt(toTextField.getText());
        }catch(NumberFormatException e){
             i=start1;
             f=end1;
        }
        long totalExp=0;
        for(int j=i;j<f;j++){
            totalExp+=(long)m.getData().get(j).getExp();
        }
        long blueSoul=10*(totalExp/100);
        long purpleSoul=10*(totalExp/222);
        long yellowSoul=10*(totalExp/650);
        long redSoul=10*(totalExp/3500);
        long gold=10*(totalExp/600);
        
        bluesoulLabel.setText("Blue souls : "+blueSoul);
        purpleSoulLabel.setText("Purple souls : "+purpleSoul);
        yellowSoulLabel.setText("Yellow souls : "+yellowSoul);
        redSoulLabel.setText("Red souls : "+redSoul);
        goldLabel.setText("Gold : "+gold);
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BonusLabel1;
    private javax.swing.JLabel BonusLabel2;
    private javax.swing.JLabel BonusLabel3;
    private javax.swing.JLabel BonusLabel4;
    private javax.swing.JLabel BonusLabel5;
    private javax.swing.JLabel Foto1;
    private javax.swing.JLabel Foto2;
    private javax.swing.JLabel Foto3;
    private javax.swing.JLabel Foto4;
    private javax.swing.JLabel Foto5;
    private javax.swing.JLabel bluesoulLabel;
    private javax.swing.JLabel bond1;
    private javax.swing.JLabel bond2;
    private javax.swing.JLabel bond3;
    private javax.swing.JLabel bond4;
    private javax.swing.JLabel bond5;
    private javax.swing.JLabel bonus1;
    private javax.swing.JLabel bonus2;
    private javax.swing.JLabel bonus3;
    private javax.swing.JLabel bonus4;
    private javax.swing.JLabel bonus5;
    private javax.swing.JLabel bonusLabel;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JTextField fromTextField;
    private javax.swing.JLabel goldLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable13;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JLabel purpleSoulLabel;
    private javax.swing.JLabel redSoulLabel;
    private javax.swing.JLabel toLabel;
    private javax.swing.JTextField toTextField;
    private javax.swing.JLabel yellowSoulLabel;
    // End of variables declaration//GEN-END:variables


    DefaultTableModel marco = new DefaultTableModel(){
			@Override
			public boolean isCellEditable(int row, int column) {
				return false;
			}
		};
 DefaultTableModel marcos []=new DefaultTableModel[5];
 private TableListener tableOnUse=null;
 NinjaBond start=null;
 NinjaBond end=null;
 int start1=0;
 int end1=0;
 private void Table1MouseClicked(java.awt.event.MouseEvent evt){
    TableListener tableSelected=listeners[0];
     if(tableOnUse==null || tableOnUse!=tableSelected){
         start1=0;
        end1=0;
        tableOnUse=tableSelected;
        start1=jTable1.getSelectedRow();
        start=m.getBond(start1,tableSelected.getBondname());
        if(start!=null){
           fromLabel.setText("<html>"+createLabel(start)); 
           fromTextField.setText(""+(start1+1));
           toLabel.setText("");
           toTextField.setText(""+1);
        }
        
     }else{
         int aux=jTable1.getSelectedRow();
         if(end==null){
              end1=jTable1.getSelectedRow();
              end=m.getBond(end1,tableSelected.getBondname());
                if(end!=null){
                   toLabel.setText("<html>"+createLabel(end)); 
                   toTextField.setText(""+(end1+1));
                }
                
         }else if(aux<start1 || (aux>start1 && aux<end1 )){
             start=m.getBond(aux,tableSelected.getBondname());
             if(start!=null){
                fromLabel.setText("<html>"+createLabel(start)); 
                fromTextField.setText(""+(start1+1));
             }
             start1=aux;
         }else{
             end=m.getBond(aux,tableSelected.getBondname());
                if(end!=null){
                  toLabel.setText("<html>"+createLabel(end)); 
                  toTextField.setText(""+(end1+1));
                  end1=aux;
                }
                
         }
         
         if(start.getLevel()<end.getLevel()){
             calcularBonus(start,end,tableSelected.getBondname());
         }
         
         
     }

 }
 
 private String createLabel(NinjaBond n) {
        String text="";
        text+="Name  : "+n.getBondname()+"<br>";
        text+="Level : "+n.getLevel()+"<br>";
        text+="Stats : "+n.getStats()+"<br>"+n.getTipoBonus()+"<br>";
        return text;
 }
 
 
 
 private void Table2MouseClicked(java.awt.event.MouseEvent evt){
TableListener tableSelected=listeners[1];
     if(tableOnUse==null || tableOnUse!=tableSelected){
         start1=0;
        end1=0;
        tableOnUse=tableSelected;
        start1=jTable2.getSelectedRow();
        start=m.getBond(start1,tableSelected.getBondname());
        if(start!=null){
           fromLabel.setText("<html>"+createLabel(start)); 
           fromTextField.setText(""+(start1+1));
           toLabel.setText("");
           toTextField.setText(""+1);
        }
        
     }else{
         int aux=jTable2.getSelectedRow();
         if(end==null){
              end1=jTable2.getSelectedRow();
              end=m.getBond(end1,tableSelected.getBondname());
                if(end!=null){
                   toLabel.setText("<html>"+createLabel(end)); 
                   toTextField.setText(""+(end1+1));
                }
                
         }else if(aux<start1 || (aux>start1 && aux<end1 )){
             start=m.getBond(aux,tableSelected.getBondname());
             if(start!=null){
                fromLabel.setText("<html>"+createLabel(start)); 
                fromTextField.setText(""+(start1+1));
             }
             start1=aux;
         }else{
             end=m.getBond(aux,tableSelected.getBondname());
                if(end!=null){
                  toLabel.setText("<html>"+createLabel(end)); 
                  toTextField.setText(""+(end1+1));
                  end1=aux;
                }
                
         }
         
         if(start.getLevel()<end.getLevel()){
             calcularBonus(start,end,tableSelected.getBondname());
         }
         
         
     }
 }
 private void Table3MouseClicked(java.awt.event.MouseEvent evt){
TableListener tableSelected=listeners[2];
     if(tableOnUse==null || tableOnUse!=tableSelected){
        tableOnUse=tableSelected;
        start1=0;
        end1=0;
        start1=jTable3.getSelectedRow();
        start=m.getBond(start1,tableSelected.getBondname());
        if(start!=null){
           fromLabel.setText("<html>"+createLabel(start)); 
           fromTextField.setText(""+(start1+1));
           toLabel.setText("");
           toTextField.setText(""+1);
        }
        
     }else{
         int aux=jTable3.getSelectedRow();
         if(end==null){
              end1=jTable3.getSelectedRow();
              end=m.getBond(end1,tableSelected.getBondname());
                if(end!=null){
                   toLabel.setText("<html>"+createLabel(end)); 
                   toTextField.setText(""+(end1+1));
                }
                
         }else if(aux<start1 || (aux>start1 && aux<end1 )){
             start=m.getBond(aux,tableSelected.getBondname());
             if(start!=null){
                fromLabel.setText("<html>"+createLabel(start)); 
                fromTextField.setText(""+(start1+1));
             }
             start1=aux;
         }else{
             end=m.getBond(aux,tableSelected.getBondname());
                if(end!=null){
                  toLabel.setText("<html>"+createLabel(end)); 
                  toTextField.setText(""+(end1+1));
                  end1=aux;
                }
                
         }
         
         if(start.getLevel()<end.getLevel()){
             calcularBonus(start,end,tableSelected.getBondname());
         }
         
         
     }
 }
 private void Table4MouseClicked(java.awt.event.MouseEvent evt){
TableListener tableSelected=listeners[3];
     if(tableOnUse==null || tableOnUse!=tableSelected){
         start1=0;
        end1=0;
        tableOnUse=tableSelected;
        start1=jTable4.getSelectedRow();
        start=m.getBond(start1,tableSelected.getBondname());
        if(start!=null){
           fromLabel.setText("<html>"+createLabel(start)); 
           fromTextField.setText(""+(start1+1));
           toLabel.setText("");
           toTextField.setText(""+1);
        }
        
     }else{
         int aux=jTable4.getSelectedRow();
         if(end==null){
              end1=jTable4.getSelectedRow();
              end=m.getBond(end1,tableSelected.getBondname());
                if(end!=null){
                   toLabel.setText("<html>"+createLabel(end)); 
                   toTextField.setText(""+(end1+1));
                }
                
         }else if(aux<start1 || (aux>start1 && aux<end1 )){
             start=m.getBond(aux,tableSelected.getBondname());
             if(start!=null){
                fromLabel.setText("<html>"+createLabel(start)); 
                fromTextField.setText(""+(start1+1));
             }
             start1=aux;
         }else{
             end=m.getBond(aux,tableSelected.getBondname());
                if(end!=null){
                  toLabel.setText("<html>"+createLabel(end)); 
                  toTextField.setText(""+(end1+1));
                  end1=aux;
                }
                
         }
         
         if(start.getLevel()<end.getLevel()){
             calcularBonus(start,end,tableSelected.getBondname());
         }
         
         
     }
 }
 private void Table5MouseClicked(java.awt.event.MouseEvent evt){
TableListener tableSelected=listeners[4];
     if(tableOnUse==null || tableOnUse!=tableSelected){
         start1=0;
        end1=0;
        tableOnUse=tableSelected;
        start1=jTable5.getSelectedRow();
        start=m.getBond(start1,tableSelected.getBondname());
        if(start!=null){
           fromLabel.setText("<html>"+createLabel(start)); 
           fromTextField.setText(""+(start1+1));
           toLabel.setText("");
           toTextField.setText(""+1);
        }
        
     }else{
         int aux=jTable5.getSelectedRow();
         if(end==null){
              end1=jTable5.getSelectedRow();
              end=m.getBond(end1,tableSelected.getBondname());
                if(end!=null){
                   toLabel.setText("<html>"+createLabel(end)); 
                   toTextField.setText(""+(end1+1));
                }
                
         }else if(aux<start1 || (aux>start1 && aux<end1 )){
             start=m.getBond(aux,tableSelected.getBondname());
             if(start!=null){
                fromLabel.setText("<html>"+createLabel(start)); 
                fromTextField.setText(""+(start1+1));
             }
             start1=aux;
         }else{
             end=m.getBond(aux,tableSelected.getBondname());
                if(end!=null){
                  toLabel.setText("<html>"+createLabel(end)); 
                  toTextField.setText(""+(end1+1));
                  end1=aux;
                }
                
         }
         
         if(start.getLevel()<end.getLevel()){
             calcularBonus(start,end,tableSelected.getBondname());
         }
         
         
     }
 }
 
 private TableListener[] listeners= new TableListener[5];
 private void setLevels() {
     
        for(int i=0;i<marcos.length;i++){
            marcos[i]= new DefaultTableModel(){
			@Override
			public boolean isCellEditable(int row, int column) {
				return false;
			}
		};
        }
        
        jTable1.setModel(marcos[0]);
        jScrollPane1.setViewportView(jTable1);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table1MouseClicked(evt);
            }
        });
        jTable2.setModel(marcos[1]);
        jScrollPane3.setViewportView(jTable2);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table2MouseClicked(evt);
            }
        });
        jTable3.setModel(marcos[2]);
        jScrollPane4.setViewportView(jTable3);
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table3MouseClicked(evt);
            }
        });
        jTable4.setModel(marcos[3]);
        jScrollPane5.setViewportView(jTable4);
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table4MouseClicked(evt);
            }
        });
        jTable5.setModel(marcos[4]);
        jScrollPane6.setViewportView(jTable5);
        jTable5.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table5MouseClicked(evt);
            }
        });
        String [][] table;//=createTable();
        String [] titulos= new String []{
         "Level", "stats","Exp",  
        };
        int i=0;
        for(DefaultTableModel m1:marcos){
            for(String s :titulos){
                  m1.addColumn(s);
            }
            i++;
        }
        i=0;
        String ruta="/Imagenes/Bonds/";
        ruta+=name+"/";
        Foto1.setIcon(new javax.swing.ImageIcon(getClass().getResource(ruta+order[0]+".PNG")));
        Foto2.setIcon(new javax.swing.ImageIcon(getClass().getResource(ruta+order[1]+".PNG")));
        Foto3.setIcon(new javax.swing.ImageIcon(getClass().getResource(ruta+order[2]+".PNG")));
        Foto4.setIcon(new javax.swing.ImageIcon(getClass().getResource(ruta+order[3]+".PNG")));
        Foto5.setIcon(new javax.swing.ImageIcon(getClass().getResource(ruta+order[4]+".PNG")));
        
        for(String s1: order){
            table=createTable(s1);
            for(String [] s : table){
                marcos[i].addRow(s);
            }
            i++;
        }
        bond1.setText(order[0]);
        bond2.setText(order[1]);
        bond3.setText(order[2]);
        bond4.setText(order[3]);
        bond5.setText(order[4]);
        
        
        bonus1.setText(m.obtenerBonus(order[0]));
        listeners[0]= new TableListener(jTable1,bonus1.getText(),order[0]);
        bonus2.setText(m.obtenerBonus(order[1]));
        listeners[1]= new TableListener(jTable2,bonus2.getText(),order[1]);
        bonus3.setText(m.obtenerBonus(order[2]));
        listeners[2]= new TableListener(jTable3,bonus3.getText(),order[2]);
        bonus4.setText(m.obtenerBonus(order[3]));
        listeners[3]= new TableListener(jTable4,bonus4.getText(),order[3]);
        if(this.name.equals("Akatsuki")){
        bonus5.setText(m.obtenerBonus(order[4]));
        listeners[4]= new TableListener(jTable5,bonus5.getText(),order[4]);
        }else{
        bonus5.setText("Team effect "+m.obtenerBonus2(name)+"%");
        }
        
        NinjaBond a= m.getBond2(name);
        if(a!=null){
            BonusLabel1.setText("Activate any 1 super bond to increase vangaurds  hp by "+a.getHp()+" points");
            BonusLabel2.setText("Activate any 2 super bond to increase assaulters attack by "+a.getAssaulterAttack()+" points");
            BonusLabel3.setText("Activate any 3 super bond to increase supports speed by "+a.getSpeed()+" points");
            BonusLabel4.setText("Activate any 4 super bond to increase all allies attack by "+a.getAttack()+" points");
            BonusLabel5.setText("Activate any 5 super bond to increase all allies defense "+a.getDefense()+" points");
        }

    }
    private String [][] createTable(String name){
        ArrayList <NinjaBond> aux=m.getFiltred(name);
      
        String matriz[][]=new String[aux.size()][3];
       
        
        for(int i=0;i<aux.size();i++){
            matriz[i][0]=""+aux.get(i).getLevel();
            matriz[i][1]=""+aux.get(i).getStats();
            matriz[i][2]=""+aux.get(i).getExp();
          
        }
        return matriz;
    }

    private void calcularBonus(NinjaBond start, NinjaBond end,String name) {
        NinjaBond aux=m.getDiference(start,end,name);
        bonusLabel.setText("<html>"+createLabel(aux));
    }

    


}
