/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Model.Senjutsu;
import Model.RepositorioWings;
import Model.Wings;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Todomelocomo
 */
public class WingsPanel extends javax.swing.JPanel {

    /**
     * Creates new form WingsPanel
     */
    RepositorioWings m;
    public WingsPanel(ArrayList <Wings> m) {
        initComponents();
        this.m=new RepositorioWings(m);
        setLevels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalExpLabel = new javax.swing.JLabel();
        statsLabel = new javax.swing.JLabel();
        calculateButton = new javax.swing.JButton();
        statsLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        startLevelTextField = new javax.swing.JTextField();
        colorfulPlumeLabel = new javax.swing.JLabel();
        endLevel = new javax.swing.JLabel();
        endLevelTextField = new javax.swing.JTextField();
        bonusStatsLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        initialExplTextField = new javax.swing.JTextField();
        endLevel1 = new javax.swing.JLabel();

        totalExpLabel.setText("Total Exp needed ");

        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LevelPanel/Wings/Colorful_plume.PNG"))); // NOI18N
        jLabel6.setText("jLabel6");

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.setModel(marco);
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        jLabel1.setText("Start level");

        startLevelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startLevelTextFieldActionPerformed(evt);
            }
        });

        colorfulPlumeLabel.setText("Colorful plume : 0");

        endLevel.setText("End  level");

        endLevelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endLevelTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("From");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("To");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Bonus");

        initialExplTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initialExplTextFieldActionPerformed(evt);
            }
        });

        endLevel1.setText("Initial exp");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(138, 138, 138)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(statsLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                                        .addComponent(statsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(126, 126, 126)
                                        .addComponent(startLevelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(endLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55)
                                        .addComponent(endLevelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(46, 46, 46)
                                            .addComponent(colorfulPlumeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(totalExpLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(118, 118, 118))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(endLevel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(initialExplTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bonusStatsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startLevelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(endLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endLevelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(endLevel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(initialExplTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addComponent(totalExpLabel)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(colorfulPlumeLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(statsLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(statsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calculateButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bonusStatsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        // TODO add your handling code here:
        if(startLevelTextField.getText().isEmpty() || endLevelTextField.getText().isEmpty()){
            
        }else{
            
        
        start=m.getLevel(startLevelTextField.getText());
        end=m.getLevel(endLevelTextField.getText());
        start1=m.getConcretWing(startLevelTextField.getText());
        end1=m.getConcretWing(endLevelTextField.getText());
        if(start1!=null && end1!=null){
             long totalExp=0;
            for(int i=start;i<end;i++){
                totalExp+=m.getData().get(i).getExp();
            }
            int ini;
            if(initialExplTextField.getText().isEmpty()){
                ini=0;
            }else{
                ini=Integer.parseInt(initialExplTextField.getText());
            }
            int colorfulPlume=(int) ((totalExp-ini)/20);
            totalExpLabel.setText("Totatl exp needed "+(totalExp-ini));
            colorfulPlumeLabel.setText("Colorful plume : "+colorfulPlume);
            statsLabel1.setText("<html>"+setStatsLabel(start1));
            statsLabel.setText("<html>"+setStatsLabel(end1));
            bonusStatsLabel.setText("<html>"+createBonusLabel(start1,end1));
        }
       
        
        }
        

    }//GEN-LAST:event_calculateButtonActionPerformed
    int start=-1;
    int end=-1;
    Wings start1,end1;
    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked

        DefaultTableModel modelo = (DefaultTableModel) Table.getModel();
        int fila=Table.getSelectedRow();
        Wings aux= m.getData().get(fila);

        if(start==-1 || fila<start){
            start1=aux;
            start=fila;
            startLevelTextField.setText(start1.getName());
            statsLabel1.setText("<html>"+setStatsLabel(aux));
        }else if(end==-1 || fila>end ){
            end1=aux;
            end=fila;
            endLevelTextField.setText(end1.getName());
            statsLabel.setText("<html>"+setStatsLabel(aux));
        }else{
            start1=aux;
            start=fila;
            startLevelTextField.setText(start1.getName());
            statsLabel1.setText("<html>"+setStatsLabel(aux));
        }
        
        if(start!=-1 && end!=-1){
            
            bonusStatsLabel.setText("<html>"+createBonusLabel(start1,end1));
        }
    }//GEN-LAST:event_TableMouseClicked

    private String createBonusLabel(Wings start1, Wings end1) {
        
        Wings aux=new Wings();
        aux.setForce(end1.getForce()-start1.getForce());
        aux.setChakra(end1.getChakra()-start1.getChakra());
        aux.setAgi(end1.getAgi()-start1.getAgi());
        aux.setPower(end1.getPower()-start1.getPower());
        int dr=Integer.parseInt(end1.getDamageRate().replace("%", ""))-Integer.parseInt(start1.getDamageRate().replace("%", ""));
        int ai=Integer.parseInt(end1.getAvoidInjury().replace("%", ""))-Integer.parseInt(start1.getAvoidInjury().replace("%", ""));
        aux.setDamageRate(dr+"%");
        aux.setAvoidInjury(ai+"%");
        System.out.println(aux.toString());
        
        String text="";
        text+="Force        : "+aux.getForce()+"<br>";
        text+="Chakra       : "+aux.getChakra()+"<br>";
        text+="Agi          : "+aux.getAgi()+"<br>";
        text+="Power        : "+aux.getPower()+"<br>";
        text+="Damage rate  : "+aux.getDamageRate()+"<br>";
        text+="Avoid injury : "+aux.getAvoidInjury()+"<br>";
        return text; 
       
        
    }
    
     private String setStatsLabel(Wings aux) {
        String text="";
        text+="Level        : "+aux.getName()+"<br>";
        text+="Exp level    : "+aux.getExp()+"<br>";
        text+="Force        : "+aux.getForce()+"<br>";
        text+="Chakra       : "+aux.getChakra()+"<br>";
        text+="Agi          : "+aux.getAgi()+"<br>";
        text+="Power        : "+aux.getPower()+"<br>";
        text+="Damage rate  : "+aux.getDamageRate()+"<br>";
        text+="Avoid injury : "+aux.getAvoidInjury()+"<br>";
        return text;  
        
    }
    private void startLevelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startLevelTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startLevelTextFieldActionPerformed

    private void endLevelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endLevelTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endLevelTextFieldActionPerformed

    private void initialExplTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initialExplTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_initialExplTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JLabel bonusStatsLabel;
    private javax.swing.JButton calculateButton;
    private javax.swing.JLabel colorfulPlumeLabel;
    private javax.swing.JLabel endLevel;
    private javax.swing.JLabel endLevel1;
    private javax.swing.JTextField endLevelTextField;
    private javax.swing.JTextField initialExplTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField startLevelTextField;
    private javax.swing.JLabel statsLabel;
    private javax.swing.JLabel statsLabel1;
    private javax.swing.JLabel totalExpLabel;
    // End of variables declaration//GEN-END:variables

    DefaultTableModel marco = new DefaultTableModel(){
			@Override
			public boolean isCellEditable(int row, int column) {
				return false;
			}
		};
    private void setLevels() {
        String [][] table=createTable();
        String [] titulos= new String []{
          "Level","Exp level",
        };
        
        for(String s :titulos){
              marco.addColumn(s);
        }
        for(String [] s : table){
            marco.addRow(s);
        }
    }
    private String [][] createTable(){
        String matriz[][]=new String[m.getData().size()][2];
       
        ArrayList <Wings> aux=m.getData();
        for(int i=0;i<aux.size();i++){
            
            matriz[i][0]=aux.get(i).getName();
            matriz[i][1]=String.format("%d", aux.get(i).getExp());
          
            
        }
        return matriz;
    }

    









}
