
import Vistas.levelPanel;
import Vistas.potencyPanel;
import java.io.IOException;
import Model.Model;
import Vistas.BondPanel;
import Vistas.JadePanel;
import Vistas.SenjutsuPanel;
import Vistas.SummonPanel;
import Vistas.SweaponPanel;
import Vistas.WingsPanel;
import java.util.logging.Level;
import java.util.logging.Logger;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Todomelocomo
 */
public class practica1 extends javax.swing.JFrame {

    /**
     * Creates new form practica1
     */
    Model m;
    public practica1() throws IOException {
        initComponents();
        m=new Model();
        importar();
        AddPanels();
        
    }
    
      public void importar() throws IOException{
       m.importLevelsBBDD();
     m.importSweaponsBBDD();
       m.importbondBBDD();
       m.importpotencyBBDD();
       m.importsenjutsuLevelsBBDD();
       m.importsummonlevelsBBDD();
       m.importwingsBBDD();
    }
    /*
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        principal.setPreferredSize(new java.awt.Dimension(652, 515));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, 1150, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(practica1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(practica1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(practica1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(practica1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new practica1().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(practica1.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane principal;
    // End of variables declaration//GEN-END:variables
    private levelPanel p1;
    private potencyPanel p2;
    private JadePanel p3;
    private SweaponPanel p4;
    private SenjutsuPanel p5;
    private WingsPanel p6;
    private SummonPanel p7;
    private BondPanel p8;
    private void AddPanels() {
       p1= new levelPanel(m);
       principal.addTab("Level", p1);
       p2=new potencyPanel(m);
       principal.addTab("Potency", p2);
       p3=new JadePanel();
       principal.addTab("Jades", p3);
       p4=new SweaponPanel(m);
       principal.addTab("Sweapon", p4);
       p5=new SenjutsuPanel(m.getSenjutsuLevels());
       principal.addTab("Senjutsu", p5);
       p6=new WingsPanel(m.getWings());
       principal.addTab("Wings", p6);
       p7=new SummonPanel(m.getSummonLevels());
       principal.addTab("SummonBeast", p7);
       p8=new BondPanel(m.getBonds());
       principal.addTab("Bonds", p8);
    }
}
